
function  terminating_pts1=putout_ex2( zd,terminating_pts)
% zd=rgb2gray(zdRGB);

terminating_pts1=terminating_pts;
for i=1: size(terminating_pts)
   
% % %    %if zd(terminating_pts(i,1),terminating_pts(i,2))==0,%%%not correct 
% % %       if zd(terminating_pts(i,2),terminating_pts(i,1))==0,

    if (zd(terminating_pts(i,2),terminating_pts(i,1))==0 && ...
        zd(terminating_pts(i,2)+1,terminating_pts(i,1))==0 && ...
        zd(terminating_pts(i,2),terminating_pts(i,1)+1)==0 &&...
         zd(terminating_pts(i,2)+2,terminating_pts(i,1))==0 &&...
         zd(terminating_pts(i,2),terminating_pts(i,1)+2)==0 &&...
          zd(terminating_pts(i,2)-1,terminating_pts(i,1))==0 &&...
         zd(terminating_pts(i,2),terminating_pts(i,1)-1)==0 &&...
         zd(terminating_pts(i,2)-2,terminating_pts(i,1))==0 &&...
         zd(terminating_pts(i,2),terminating_pts(i,1)-2)==0 &&...
         zd(terminating_pts(i,2)+1,terminating_pts(i,1)+1)==0 &&...
         zd(terminating_pts(i,2)+1,terminating_pts(i,1)+2)==0 &&...
         zd(terminating_pts(i,2)+2,terminating_pts(i,1)+2)==0 &&...
          zd(terminating_pts(i,2)+2,terminating_pts(i,1)+1)==0 &&...%
          zd(terminating_pts(i,2)+1,terminating_pts(i,1)-1)==0 &&...
         zd(terminating_pts(i,2)+1,terminating_pts(i,1)-2)==0 &&...
         zd(terminating_pts(i,2)+2,terminating_pts(i,1)-2)==0 &&...
          zd(terminating_pts(i,2)+2,terminating_pts(i,1)-1)==0 &&...
          zd(terminating_pts(i,2)-1,terminating_pts(i,1)-1)==0 &&...
         zd(terminating_pts(i,2)-1,terminating_pts(i,1)-2)==0 &&...
         zd(terminating_pts(i,2)-2,terminating_pts(i,1)-2)==0 &&...
          zd(terminating_pts(i,2)-2,terminating_pts(i,1)-1)==0 &&...
          zd(terminating_pts(i,2)+1,terminating_pts(i,1)+1)==0 &&...
         zd(terminating_pts(i,2)+1,terminating_pts(i,1)+2)==0 &&...
         zd(terminating_pts(i,2)+2,terminating_pts(i,1)+2)==0 &&...
          zd(terminating_pts(i,2)+2,terminating_pts(i,1)+1)==0)
% %           %%%%%%%%%do
        terminating_pts1(i,1:2)=0;
        
     end
end

sl=size(terminating_pts1);
%terminating_pts2=terminating_pts1;
i=1;
while i<=sl(1,1)
   
    if terminating_pts1(i,1)==0,
        terminating_pts1(i,:)=[];
        sl=sl-1;
    else    i=i+1;
    end
end